### ISSUE TITLE
Integrate JSON schema into library

### ISSUE THREAD

**Issue by fabianburth** [open-component-model/ocm-project#213] opened 2024-06-18 08:01 UTC
**Description**
Follow up task for #198 

**Done Criteria**
- [ ] ...
- [ ] Code has been reviewed by other team members
- [ ] Internal technical Documentation created/updated
- [ ] New / changed code is documented
- [ ] Analysis of existing tests (Unit and Integration)
- [ ] Unit Tests created for new code or existing Unit Tests updated
- [ ] Integration Test Suite updated (includes deletion of existing unnecessary Integration Test and/or creation of new ones if required)
- [ ] Enduser Documentation updated (if applicable)
- [ ] Successful demonstration in Review

**Comment by morri-son** [comment] 2024-10-18 08:48
duplicate of https://github.com/open-component-model/ocm-project/issues/9

**Closed by morri-son** 2024-10-18 08:48 UTC
Labels: kind/task
